sudo: false
language: node_js
node_js:
  - "5"
  - "4"
  - "0.12"
  - "0.10"
before_script:
  - npm i -g verb-readme-generator
matrix:
  fast_finish: true
  allow_failures:
    - node_js: "0.10"
    - node_js: "0.12"
